name: 'Build Windows Executable'
description: 'Builds the Zed executable for Windows'
runs:
  using: 'composite'
  steps:
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        target: x86_64-pc-windows-msvc

    - name: Install dependencies
      shell: powershell
      run: |
        choco install llvm -y
        
    - name: Build Zed executable
      shell: powershell
      run: |
        cargo build --release --bin zed
        
    - name: Package executable
      shell: powershell
      run: |
        mkdir -p dist
        cp target/release/zed.exe dist/
        
        # Copy necessary runtime DLLs if needed
        # cp some-required-dll.dll dist/
