name: 'Build Windows Executable'
description: 'Builds the Zed executable for Windows'
runs:
  using: 'composite'
  steps:
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: x86_64-pc-windows-msvc
        components: clippy, rustfmt

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "15.0"

    - name: Install additional dependencies
      shell: powershell
      run: |
        # Install required Windows-specific dependencies
        # Use VS Build Tools installer instead of winget
        $installerUrl = "https://aka.ms/vs/17/release/vs_buildtools.exe"
        $installerPath = "$env:TEMP\vs_buildtools.exe"
        Invoke-WebRequest -Uri $installerUrl -OutFile $installerPath
        
        # Install necessary components for C++ development
        Start-Process -FilePath $installerPath -ArgumentList `
          "--quiet", "--wait", "--norestart", `
          "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64", `
          "--add Microsoft.VisualStudio.Component.Windows10SDK.19041" `
          -Wait -NoNewWindow
        
        # Verify installation 
        if (!(Test-Path "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC")) {
            Write-Warning "Visual Studio Build Tools installation may have failed."
        }
        
        # Enable long paths in Windows and Git
        git config --system core.longpaths true
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -Type DWord

    - name: Set up shorter paths for Cargo
      shell: powershell
      run: |
        # Create shorter path for cargo cache
        New-Item -ItemType Directory -Force -Path "C:\cr"
        $env:CARGO_HOME = "C:\cr"
        echo "CARGO_HOME=C:\cr" | Out-File -FilePath $env:GITHUB_ENV -Append
        
        # Create shorter path for build target
        New-Item -ItemType Directory -Force -Path "C:\zb"
        echo "CARGO_TARGET_DIR=C:\zb" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          C:\cr
          C:\zb
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build Zed executable
      shell: powershell
      run: |
        $env:RUSTFLAGS = "-C target-feature=+crt-static"
        # Skip building pet-related dependencies that have path issues
        cargo build --release --bin zed --no-default-features
        if (-not $?) { throw "Build failed" }
        
    - name: Verify build output
      shell: powershell
      run: |
        if (-not (Test-Path "target/release/zed.exe")) {
          throw "Build output not found"
        }
        
    - name: Package executable
      shell: powershell
      run: |
        New-Item -ItemType Directory -Force -Path "dist"
        Copy-Item "target/release/zed.exe" -Destination "dist/"
        
        # Copy assets folder if needed
        if (Test-Path "assets") {
          Copy-Item -Path "assets" -Destination "dist/" -Recurse
        }
        
        # Copy any required DLLs or configurations
        if (Test-Path "crates/zed/config") {
          Copy-Item -Path "crates/zed/config" -Destination "dist/" -Recurse
        }
        
        # Create a zip archive of the distribution
        Compress-Archive -Path "dist/*" -DestinationPath "zed-windows.zip" -Force
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: zed-windows
        path: zed-windows.zip
        retention-days: 7
